# Generated by Django 5.0.2 on 2025-05-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transac_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgement',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='acknowledgements/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, upload_to='proof/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
