# Generated by Django 5.0.2 on 2025-05-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transac_app', '0002_acknowledgement_data_acknowledgement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ack/'),
        ),
    ]
