# Generated by Django 5.0.2 on 2025-05-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transac_app', '0003_alter_acknowledgement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
